name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore Blogifier/src/Blogifier/Blogifier.csproj
    - name: Build
      run: dotnet build Blogifier/src/Blogifier/Blogifier.csproj --no-restore

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish Blogifier/src/Blogifier/Blogifier.csproj -c Release -o bin/Release --nologo

    # changes the base-tag in index.html from '/' to 'Blogifier' to match GitHub Pages repository subdirectory
    #- name: Change base-tag in index.html from / to blog
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/blog\/" \/>/g' bin/Release/wwwroot/index.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch bin/Release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: bin/Release/wwwroot

    #- name: Tests
    #  run: dotnet test Blogifier/tests/Blogifier.Tests